---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-end
  namespace: sock-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: front-end

  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
    
