---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-end
  namespace: sock-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: front-end

  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orders
  namespace: sock-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: orders

  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
  namespace: sock-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: shipping

  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user
  namespace: sock-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: user

  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cart
  namespace: sock-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: carts
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
